version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql-service
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    restart: unless-stopped
