name: Services Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: codebuild-gha-runner-${{ github.run_id }}-${{ github.run_attempt }}
    container: golang:1.21
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Go script
        working-directory: ./app
        env:
          DB_HOST: mysql
          DB_PORT: 3306
        run: |
         go mod tidy
         sleep 30
         go run main.go

