name: Docker Compose Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: codebuild-gha-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose up -d

      - name: Wait for services to be ready
        run: sleep 10

      - name: List running containers
        run: docker ps

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run Go script
        working-directory: ./app
        run: |
         go mod tidy
         go run main.go

      - name: Tear down Docker Compose
        run: docker compose down

